#!/bin/zsh

# This file is sourced in login shells. Environmental variables are set here.

export PATH="$PATH:${$(find ~/.local/bin -type d -printf %p:)%%:}"

# Default programs.
export EDITOR='vim'
export PAGER='less'
export TERMINAL='alacritty'
export BROWSER='brave'

# ~/ Clean-up.
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"

export XINITRC="${XDG_CONFIG_HOME:-$HOME/.config}/x11/xinitrc"
export GTK2_RC_FILES="${XDG_CONFIG_HOME:-$HOME/.config}/gtk-2.0/gtkrc"
export WGETRC="$XDG_CONFIG_HOME/wget/wgetrc"
export LESSHISTFILE="-"
export ZDOTDIR="${XDG_CONFIG_HOME:-$HOME/.config}/zsh"
export TMUX_TMPDIR="$XDG_RUNTIME_DIR"
export CARGO_HOME="${XDG_DATA_HOME:-$HOME/.local/share}/cargo"
export GOPATH="${XDG_DATA_HOME:-$HOME/.local/share}/go"
export HISTFILE="${XDG_DATA_HOME:-$HOME/.local/share}/history"

export ASDF_CONFIG_FILE="${XDG_CONFIG_HOME:-$HOME/.config}/asdf/asdfrc"
export ASDF_DIR=/opt/asdf-vm
export ASDF_DATA_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/asdf"
export ASDF_GEM_DEFAULT_PACKAGES_FILE="${XDG_CONFIG_HOME:-$HOME/.config}/gem/default-gems"

export GEMRC="${XDG_CONFIG_HOME:-$HOME/.config}/gem/gemrc"
export GEM_SPEC_CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/gem/specs"

export GIT_TEMPLATE_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/git/template"

export BUNDLE_USER_HOME="${XDG_CACHE_HOME:-$HOME/.cache}/bundle"

export NPM_CONFIG_USERCONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/npm/npmrc"
export NPM_CONFIG_CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/npm"
export NPM_CONFIG_DEVDIR="${XDG_CACHE_HOME:-$HOME/.cache}/gyp"

export RANDFILE="${XDG_CACHE_HOME:-$HOME/.cache}/rnd"
export DOCKER_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/docker"
export PSQLRC="${XDG_CONFIG_HOME:-$HOME/.config}/psql/psqlrc"

# Other program settings
export FZF_DEFAULT_OPTS="--layout=reverse --height 40%"

# M Display line numbers and position.
# Q Never ring terminal bell.
# R Display color escape chars as-is (so they're displayed).
# S Don't automatically wrap long lines.
# X Don't clear the screen on exit.
# i Ignore case unless pattern has upper case chars.
export LESS=-MQRSXi

export LANG='en_US.UTF-8'
export LESS_TERMCAP_mb="$(printf '%b' '[1;31m')"
export LESS_TERMCAP_md="$(printf '%b' '[1;36m')"
export LESS_TERMCAP_me="$(printf '%b' '[0m')"
export LESS_TERMCAP_so="$(printf '%b' '[01;44;33m')"
export LESS_TERMCAP_se="$(printf '%b' '[0m')"
export LESS_TERMCAP_us="$(printf '%b' '[1;32m')"
export LESS_TERMCAP_ue="$(printf '%b' '[0m')"
export LESSOPEN="| /usr/bin/highlight -O ansi %s 2>/dev/null"
export QT_QPA_PLATFORMTHEME="gtk2" # Have QT use gtk2 theme.
export MOZ_USE_XINPUT2="1" # Mozilla smooth scrolling/touchpads.
export AWT_TOOLKIT="MToolkit wmname LG3D" # May have to install wmname
export _JAVA_AWT_WM_NONREPARENTING=1 # Fix for Java applications in dwm.

# Enable color support of ls.
[ -x /usr/bin/dircolors ] && eval "$(dircolors)"

# Start graphical server on user's current tty if not already running.
[ "$(tty)" = "/dev/tty1" ] && ! pidof -s Xorg >/dev/null 2>&1 && exec startx "$XINITRC"
